package io.github.Earth1283.bashCraft.commands.util

import io.github.Earth1283.bashCraft.TerminalSession
import io.github.Earth1283.bashCraft.commands.LinuxCommand
import org.bukkit.command.CommandSender

class ManCommand : LinuxCommand("man", "Display manual pages", "man <command>", listOf("help", "rtfm")) {

    override fun run(sender: CommandSender, args: Array<String>, session: TerminalSession, pipedInput: List<String>?): List<String> {
        val cmd = args.firstOrNull() ?: return listOf(
            "What manual page do you want?",
            "Available pages: ls, pwd, cd, cat, find, stat, ps, top, free, uname, uptime, df, du,",
            "  whoami, who, w, id, ping, kill, killall, sudo, sleep, echo, grep, head, tail, sort,",
            "  uniq, wc, tr, sed, cut, date, cal, history, clear, alias, env, export, bc, yes,",
            "  factor, rev, fortune, cowsay, banner, mv, cp, touch, rm, mkdir, curl, fs",
        )

        return PAGES[cmd.lowercase()] ?: listOf("No manual entry for $cmd")
    }

    companion object {
        val PAGES: Map<String, List<String>> = mapOf(
            "ls" to page("ls", "list directory contents",
                "ls [-la] [path]",
                "List contents of the current virtual directory or a specified path.\n" +
                "In Minecraft mode: / lists worlds, /worldname lists entities/players,\n" +
                "a location path lists nearby blocks and entities.\n" +
                "In filesystem mode (/fs on): lists real files and directories.",
                "-l  use long listing format\n-a  show hidden files (dotfiles/hidden entities)\n-R  list subdirectories recursively\n-h  human-readable sizes",
                "ls\nls -la\nls /world\nls -l /world_nether\nls /world/100/64/-200"),
            "pwd" to page("pwd", "print name of current/working directory",
                "pwd",
                "Print the current working directory path.\nIn Minecraft mode: shows virtual path + player coordinates.\nIn filesystem mode: shows absolute real path.",
                "", "pwd"),
            "cd" to page("cd", "change the current directory",
                "cd [path]",
                "Change working directory. In Minecraft mode, cd to a world dir\nteleports to that world's spawn; cd to a coordinate path teleports\nthe player to that location. cd ~ goes to world spawn / server home.\nIn filesystem mode: navigate the real filesystem.",
                "", "cd world_nether\ncd /world/100/64/-200\ncd ~\ncd .."),
            "cat" to page("cat", "concatenate files and print",
                "cat [target]",
                "In Minecraft mode: reads sign text, book contents, chest inventories.\nTargets: inventory, equipment, stats, or look at a block.\nIn filesystem mode: print file contents (text only, 64KB max).",
                "", "cat inventory\ncat stats\ncat server.properties"),
            "find" to page("find", "search for files in a directory hierarchy",
                "find [path] [-name pattern] [-type type] [-size size]",
                "In Minecraft mode: find players/entities by name or type.\nIn filesystem mode: find real files matching criteria.",
                "-name  match filename pattern (supports * and ?)\n-type  filter by type (f=file, d=dir, player, zombie, etc.)\n-size  filter by size (+N, -N, N in bytes/K/M/G)\n-maxdepth N  limit search depth",
                "find / -name Steve\nfind /world -type zombie\nfind . -name '*.log' -type f"),
            "stat" to page("stat", "display file or entity status",
                "stat [path|player]",
                "Show detailed status of a block (at current gaze or path),\na player by name, or a real file in filesystem mode.",
                "", "stat Steve\nstat server.properties"),
            "ps" to page("ps", "report a snapshot of the current processes",
                "ps [-aux]",
                "Show online players as processes. PID=entity ID,\nTTY=world, STAT=gamemode (S/C/A/R), TIME=server uptime.",
                "-a  show all players\n-u  user-oriented format\n-x  include spectators",
                "ps\nps -aux\nps | grep Steve"),
            "top" to page("top", "display server task manager",
                "top",
                "Display real-time server metrics: TPS, memory, chunk/entity counts,\nand a table of online players. Does not auto-refresh.",
                "", "top"),
            "free" to page("free", "display amount of free and used JVM memory",
                "free [-m|-g|-h]",
                "Show JVM memory usage: total (max), used, free, available.",
                "-m  megabytes (default)\n-g  gigabytes\n-h  human readable\n-b  bytes\n-k  kilobytes",
                "free\nfree -h\nfree -m"),
            "uname" to page("uname", "print system information",
                "uname [-a|-r|-s|-v|-n|-m]",
                "Print server/system information.",
                "-a  all information\n-s  kernel name (Paper)\n-n  node hostname\n-r  kernel release (MC version)\n-v  kernel version\n-m  machine type (JVM arch)",
                "uname -a\nuname -r"),
            "uptime" to page("uptime", "tell how long the system has been running",
                "uptime",
                "Show current time, server uptime, player count, and TPS load averages.",
                "", "uptime"),
            "df" to page("df", "report file system disk space usage",
                "df [-h]",
                "Show disk usage and each Minecraft world as a virtual filesystem\nmounted under /mc/worldname.",
                "-h  human-readable sizes", "df\ndf -h"),
            "du" to page("du", "estimate file space usage",
                "du [-h] [world|path]",
                "Show disk usage for a world folder (Minecraft mode) or real directory\n(filesystem mode).",
                "-h  human-readable\n-s  display only total", "du\ndu -h world"),
            "whoami" to page("whoami", "print effective user ID",
                "whoami",
                "Print your player name, UUID, gamemode, OP status, and location.",
                "", "whoami"),
            "who" to page("who", "show who is logged on",
                "who",
                "Show a brief list of online players with their world and coordinates.",
                "", "who"),
            "w" to page("w", "show who is logged on and what they are doing",
                "w",
                "Show detailed player table: name, world, ping, last command.",
                "", "w"),
            "id" to page("id", "print real and effective user and group IDs",
                "id [player]",
                "Show player entity ID, UUID, permissions summary, and OP flag.\nIf no player given, shows yourself.",
                "", "id\nid Steve"),
            "ping" to page("ping", "send ICMP echo request to a player",
                "ping [player]",
                "Show a player's network latency in milliseconds with a quality rating.\nDefaults to yourself if no target given.",
                "", "ping\nping Steve"),
            "kill" to page("kill", "send a signal to a process",
                "kill [-9] <player|@selector>",
                "Kill a player or entity. Default uses damage (can be survived with\nenough health); -9 forces instant death. Supports @e[type=X] selectors.",
                "-9  force kill (SIGKILL, instant death)\n-15  normal kill (SIGTERM, default)",
                "kill Steve\nkill -9 @e[type=zombie]\nkill @a"),
            "killall" to page("killall", "kill processes by name",
                "killall <entityType>",
                "Kill all entities of a given type in the current world.\nConsole: kills in all worlds.",
                "", "killall zombie\nkillall creeper"),
            "sudo" to page("sudo", "execute a command as root",
                "sudo <command>",
                "Execute a Minecraft command as the server console (root).\nRequires bashcraft.sudo permission (OP only).",
                "", "sudo op Steve\nsudo say Hello World\nsudo stop"),
            "sleep" to page("sleep", "delay for a specified amount of time",
                "sleep <seconds>",
                "Schedule a 'wake up' message after N seconds. Max 30 seconds.\nDoes not block subsequent commands.",
                "", "sleep 5\nsleep 0.5"),
            "echo" to page("echo", "display a line of text",
                "echo [-n] [text...]",
                "Print text to output. Expands \$VARIABLE references from the\ncurrent session environment. Supports \\n, \\t escape sequences.",
                "-n  do not output trailing newline", "echo Hello World\necho \$HOME\necho -n no newline"),
            "grep" to page("grep", "print lines that match patterns",
                "grep [-ivnc] pattern [text...]",
                "Filter input lines matching a regex pattern. Works on piped input\nor literal text arguments. In filesystem mode, can read files.",
                "-i  ignore case\n-v  invert match (show non-matching)\n-n  prefix line numbers\n-c  count matching lines only\n-F  treat pattern as fixed string",
                "ps | grep Steve\nps -aux | grep -i creative\nps | grep -v Steve"),
            "head" to page("head", "output the first part of files",
                "head [-n N] [text...]",
                "Output the first N lines of input (default: 10).",
                "-n N  print first N lines", "history | head -20\nps | head -5"),
            "tail" to page("tail", "output the last part of files",
                "tail [-n N] [text...]",
                "Output the last N lines of input (default: 10).",
                "-n N  print last N lines", "history | tail -20\nps | tail -5"),
            "sort" to page("sort", "sort lines of text files",
                "sort [-rnu] [text...]",
                "Sort input lines.",
                "-r  reverse order\n-n  numeric sort\n-u  unique (remove duplicates)\n-f  ignore case\n-R  random shuffle",
                "ps | sort\nls | sort -r"),
            "uniq" to page("uniq", "report or filter out repeated lines",
                "uniq [-cdu] [text...]",
                "Remove consecutive duplicate lines.",
                "-c  prefix lines with occurrence count\n-d  only print duplicate lines\n-u  only print unique lines\n-i  ignore case",
                "ps | sort | uniq\nhistory | sort | uniq -c | sort -rn"),
            "wc" to page("wc", "print newline, word, and byte counts",
                "wc [-lwcm] [text...]",
                "Count lines, words, bytes/chars of input.",
                "-l  count lines only\n-w  count words only\n-c  count bytes\n-m  count characters",
                "ps | wc -l\necho hello world | wc -w"),
            "tr" to page("tr", "translate or delete characters",
                "tr [-ds] set1 [set2]",
                "Translate, squeeze, or delete characters. Supports ranges (a-z, A-Z, 0-9)\nand escape sequences (\\n, \\t).",
                "-d  delete characters in set1\n-s  squeeze repeated characters",
                "echo hello | tr a-z A-Z\necho hello | tr -d aeiou"),
            "sed" to page("sed", "stream editor for filtering and transforming text",
                "sed 's/pattern/replacement/[flags]' [text...]",
                "Apply substitution to each line of input. Supports s-command only:\ns/pattern/replacement/[g|i|gi]",
                "g  replace all occurrences\ni  case-insensitive match",
                "ps | sed 's/world/overworld/g'\necho hello | sed 's/l/L/g'"),
            "cut" to page("cut", "remove sections from each line of files",
                "cut [-d delim] [-f fields] [-c chars] [text...]",
                "Extract fields by delimiter or character positions.",
                "-d  field delimiter (default: tab)\n-f  fields to extract (e.g. 1,3 or 1-3)\n-c  character range (e.g. 1-10)",
                "ps | cut -f 1 -d ' '\nwhoami | cut -c 1-8"),
            "date" to page("date", "print or set the system date and time",
                "date [+format]",
                "Print current date/time and Minecraft in-game time.\nFormat: use %Y %m %d %H %M %S placeholders.",
                "+format  custom output format", "date\ndate '+%Y-%m-%d'"),
            "cal" to page("cal", "display a Minecraft lunar calendar",
                "cal",
                "Show the current Minecraft lunar cycle: day number, moon phase,\nin-game time, and a 4-week calendar grid.",
                "", "cal"),
            "history" to page("history", "display command history",
                "history [n]",
                "Show the last N commands from your session history (default: 50).\nHistory is per-player, stored in memory until logout.",
                "", "history\nhistory 20\nhistory | grep ls"),
            "clear" to page("clear", "clear the terminal screen",
                "clear",
                "Send blank lines to push previous output off-screen in the chat.",
                "", "clear"),
            "alias" to page("alias", "define or display aliases",
                "alias [name[=value]]",
                "With no arguments, list all defined aliases.\nWith name=value, define a new alias (works in pipe stages).\nAliases are per-player and reset on logout.",
                "-d name  delete an alias", "alias\nalias ll='ls -la'\nalias grep='grep -i'\nalias -d ll"),
            "env" to page("env", "print environment variables",
                "env [variable]",
                "Show all session environment variables, or a specific one.\nVariables are used by echo (\$VAR) and export.",
                "", "env\nenv HOME"),
            "export" to page("export", "set environment variables",
                "export KEY=value",
                "Set a session environment variable. Keys must be valid identifiers.\nVariables persist for the session duration.",
                "", "export MYDIR=/world\nexport GREETING=Hello"),
            "bc" to page("bc", "arbitrary precision calculator language",
                "bc <expression>",
                "Evaluate mathematical expressions. Supports +, -, *, /, %, ^ operators,\nparentheses, and functions: sqrt, abs, sin, cos, tan, log, ln, exp,\nfloor, ceil, round. Constants: pi, e.",
                "", "bc 2+2\nbc 'sqrt(2)'\nbc '(10+5)*3'\necho '2^10' | bc"),
            "yes" to page("yes", "output a string repeatedly",
                "yes [string]",
                "Output 'y' (or given string) 20 times. Hard-capped at 20 to prevent spam.",
                "", "yes\nyes hello\nyes no | head -5"),
            "factor" to page("factor", "factor numbers",
                "factor number...",
                "Print the prime factorization of each number.",
                "", "factor 360\nfactor 12 100 999"),
            "rev" to page("rev", "reverse lines characterwise",
                "rev [text...]",
                "Reverse each line of input.",
                "", "echo hello | rev\nrev racecar"),
            "fortune" to page("fortune", "print a random Minecraft fortune",
                "fortune",
                "Display a random fortune or Minecraft wisdom.",
                "", "fortune"),
            "cowsay" to page("cowsay", "configurable speaking/thinking cow",
                "cowsay [-e eyes] [-T tongue] message",
                "Generate a talking cow ASCII art with your message.",
                "-d  dead cow (xx eyes)\n-g  greedy cow (\$\$ eyes)\n-p  paranoid cow (@@ eyes)\n-s  stoned cow\n-y  young cow",
                "cowsay Hello\nfortune | cowsay\ncowsay -d Oops"),
            "banner" to page("banner", "display text as large ASCII art",
                "banner <text>",
                "Render text in 5-row tall block letters. Supports A-Z, 0-9, !?., and space.\nMax 12 characters.",
                "", "banner HELLO\nbanner 1234"),
            "mv" to page("mv", "move (rename) files",
                "mv [-fvn] source dest",
                "Move or rename files. FS mode only (/fs on). Requires bashcraft.fs.write.",
                "-f  force (overwrite destination)\n-n  no-overwrite\n-v  verbose", "mv old.log new.log\nmv *.yml backup/"),
            "cp" to page("cp", "copy files and directories",
                "cp [-rvf] source dest",
                "Copy files. Use -r for directories. FS mode only. Requires bashcraft.fs.write.",
                "-r  recursive (directories)\n-f  force overwrite\n-v  verbose", "cp server.properties server.properties.bak"),
            "touch" to page("touch", "change file timestamps / create empty file",
                "touch file...",
                "Create empty files or update timestamps. FS mode only. Requires bashcraft.fs.write.",
                "", "touch newfile.txt\ntouch notes/todo.txt"),
            "rm" to page("rm", "remove files or directories",
                "rm [-rfv] file...",
                "Delete files. Use -r for directories. FS mode only. Requires bashcraft.fs.write.\nAll deletions are logged to the server console.",
                "-r  recursive (directories)\n-f  force (ignore errors)\n-v  verbose", "rm old.log\nrm -r backup/"),
            "mkdir" to page("mkdir", "make directories",
                "mkdir [-pv] dir...",
                "Create directories. FS mode only. Requires bashcraft.fs.write.",
                "-p  make parent dirs as needed\n-v  verbose", "mkdir logs\nmkdir -p data/backups/2024"),
            "curl" to page("curl", "transfer a URL",
                "curl [-o file] [-X method] [-d body] [-H header] url",
                "Fetch a URL using HTTP. FS mode only. Requires bashcraft.fs.curl.\nResponse is printed to chat (max 200 lines). Use -o to save to file.",
                "-o FILE  save output to file\n-X METHOD  HTTP method (GET/POST/PUT/DELETE)\n-d BODY  request body\n-H HEADER  add header (Key: Value)\n-v  verbose (show response headers)\n-s  silent",
                "curl https://example.com\ncurl -o out.json https://api.example.com/data\ncurl -X POST -d '{\"key\":\"val\"}' https://api.example.com"),
            "fs" to page("fs", "toggle filesystem mode",
                "fs [on|off|status|tree [path]]",
                "Switch between Minecraft virtual-FS mode (default) and real filesystem mode.\nIn real-FS mode, ls/cd/cat/find/stat/grep/head/tail/wc/du operate on actual files.\nAdditional commands available: mv, cp, touch, rm, mkdir, curl.\nStarting path (~) is the server's working directory.",
                "on   enter real filesystem mode\noff  return to Minecraft mode\nstatus  show current mode\ntree [path]  show directory tree",
                "/fs on\n/fs off\n/fs status\n/fs tree\n/fs tree logs"),
        )

        private fun page(name: String, summary: String, synopsis: String, description: String, options: String, examples: String): List<String> {
            val lines = mutableListOf<String>()
            lines += "NAME"
            lines += "       $name - $summary"
            lines += ""
            lines += "SYNOPSIS"
            lines += "       $synopsis"
            lines += ""
            lines += "DESCRIPTION"
            description.lines().forEach { lines += "       $it" }
            if (options.isNotEmpty()) {
                lines += ""
                lines += "OPTIONS"
                options.lines().forEach { lines += "       $it" }
            }
            lines += ""
            lines += "EXAMPLES"
            examples.lines().forEach { lines += "       $it" }
            return lines
        }
    }
}
